"use client";

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
  pdf,
} from "@react-pdf/renderer";
import type { SummaryResult } from "./types";

const base = typeof window !== "undefined" ? window.location.origin : "";
Font.register({
  family: "NanumGothic",
  fonts: [
    { src: `${base}/fonts/NanumGothic-Regular.ttf`, fontWeight: "normal" },
    { src: `${base}/fonts/NanumGothic-Bold.ttf`, fontWeight: "bold" },
  ],
});

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "NanumGothic",
    fontSize: 11,
    color: "#1a1a1a",
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: "#3b82f6",
    paddingBottom: 12,
  },
  title: {
    fontSize: 20,
    fontFamily: "NanumGothic",
    fontWeight: "bold",
    color: "#1e40af",
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 9,
    color: "#6b7280",
  },
  sectionTitle: {
    fontSize: 13,
    fontFamily: "NanumGothic",
    fontWeight: "bold",
    color: "#1e40af",
    marginTop: 20,
    marginBottom: 8,
  },
  summaryText: {
    lineHeight: 1.8,
    color: "#374151",
  },
  timelineItem: {
    marginBottom: 14,
    paddingLeft: 10,
    borderLeftWidth: 3,
    borderLeftColor: "#3b82f6",
  },
  timelineHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
    gap: 8,
  },
  timestamp: {
    fontSize: 9,
    backgroundColor: "#dbeafe",
    color: "#1d4ed8",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    fontWeight: "bold",
  },
  segmentTitle: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#111827",
    flex: 1,
  },
  keyPoint: {
    fontSize: 10,
    color: "#4b5563",
    marginLeft: 10,
    marginTop: 2,
    lineHeight: 1.6,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 9,
    color: "#9ca3af",
    textAlign: "center",
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingTop: 8,
  },
});

interface PdfDocumentProps {
  result: SummaryResult;
  videoUrl: string;
}

function PdfDocument({ result, videoUrl }: PdfDocumentProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>
            {result.videoTitle || "팟캐스트 요약"}
          </Text>
          <Text style={styles.subtitle}>{videoUrl}</Text>
        </View>

        <Text style={styles.sectionTitle}>전체 요약</Text>
        <Text style={styles.summaryText}>{result.overallSummary}</Text>

        <Text style={styles.sectionTitle}>타임라인</Text>
        {result.timeline.map((point, i) => (
          <View key={i} style={styles.timelineItem}>
            <View style={styles.timelineHeader}>
              <Text style={styles.timestamp}>{point.timestamp}</Text>
              <Text style={styles.segmentTitle}>{point.title}</Text>
            </View>
            {point.keyPoints.map((kp, j) => (
              <Text key={j} style={styles.keyPoint}>
                • {kp}
              </Text>
            ))}
          </View>
        ))}

        <Text style={styles.footer}>
          Generated by Snapcast • {new Date().toLocaleDateString("ko-KR")}
        </Text>
      </Page>
    </Document>
  );
}

export async function downloadPdf(result: SummaryResult, videoUrl: string) {
  const blob = await pdf(
    <PdfDocument result={result} videoUrl={videoUrl} />
  ).toBlob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  const title = result.videoTitle?.slice(0, 30).replace(/[/\\?%*:|"<>]/g, "-") || "podcast-summary";
  a.download = `${title}.pdf`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
